# Generated by Django 3.0.8 on 2020-07-30 04:48

import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0034_auto_20200730_1248'),
        ('occurrence', '0049_auto_20200723_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='vegetationclassification',
            name='level5',
            field=models.TextField(blank=True, help_text='The fifth classification level: Overstorey', null=True, verbose_name='Overstorey'),
        ),
        migrations.AlterField(
            model_name='areaencounter',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, help_text='A point representing the area occupied by the encountered subject. If empty, the point will be calculated as the centroid of the polygon extent. If you have coordinates, click first into the map to generate GeoJSON, then insert your coordinates into the GeoJSON. Save and review!', null=True, srid=4326, verbose_name='Representative Point'),
        ),
        migrations.AlterField(
            model_name='areaencounter',
            name='source_id',
            field=models.CharField(default=uuid.UUID('ee5d6854-d21f-11ea-a056-87bd367653c6'), help_text='The ID of the record in the original source, if available.', max_length=1000, verbose_name='Source ID'),
        ),
        migrations.AlterField(
            model_name='firehistory',
            name='fire_intensity',
            field=models.CharField(choices=[('NA', 'NA'), ('no', 'No evidence of fire'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='NA', help_text='Estimated intensity of last fire on a scale from High to Low, including no evidence of fire, or leave NA if this information is not available.', max_length=100, verbose_name='Fire intensity'),
        ),
        migrations.AlterField(
            model_name='firehistory',
            name='last_fire_date',
            field=models.DateField(blank=True, help_text='The estimated date of the last fire, if evident. Choose the closest date to your estimate.', null=True, verbose_name='Date of last fire'),
        ),
        migrations.AlterField(
            model_name='plantcount',
            name='flowering_plants_percent',
            field=models.PositiveIntegerField(blank=True, help_text='The proportion of flowering plants of surveyed population in percent [0..100].', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Flowering Plants [%]'),
        ),
        migrations.AlterField(
            model_name='taxonareaencounter',
            name='taxon',
            field=models.ForeignKey(help_text='The taxonomic name of the encountered subject. Type the taxonomic or vernacular name to see available names. The autocomplete widget times out if left for too long.', on_delete=django.db.models.deletion.PROTECT, related_name='taxon_occurrences', to='taxonomy.Taxon'),
        ),
        migrations.AlterField(
            model_name='vegetationclassification',
            name='level1',
            field=models.TextField(blank=True, help_text='The first classification level: Surface', null=True, verbose_name='Surface'),
        ),
        migrations.AlterField(
            model_name='vegetationclassification',
            name='level2',
            field=models.TextField(blank=True, help_text='The second classification level: Near Surface', null=True, verbose_name='Near Surface'),
        ),
        migrations.AlterField(
            model_name='vegetationclassification',
            name='level3',
            field=models.TextField(blank=True, help_text='The third classification level: Elevated', null=True, verbose_name='Elevated'),
        ),
        migrations.AlterField(
            model_name='vegetationclassification',
            name='level4',
            field=models.TextField(blank=True, help_text='The fourth classification level: Intermediate', null=True, verbose_name='Intermediate'),
        ),
    ]
