name: DjangoCI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.6, 3.7, 3.8]
    env:
      DATABASE_URL: "postgis://tsc:tsc@localhost/tsc"
      COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}

    steps:
    - name: Setup PostgreSQL
      uses: huaxk/postgis-action@v1.0.0
      with:
        postgresql db: tsc
        postgresql user: tsc
        postgresql password: tsc

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -qq binutils libproj-dev gdal-bin

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Pandoc
      uses: r-lib/actions/setup-pandoc@v1
      with:
        pandoc-version: '2.7.3'

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/base.txt
        mkdir logs && touch logs/tsc.log

    - name: Run parallel tests and skip test coverage
      run: fab ptest

    # - name: Build documentation
    # - uses: ammaraskar/sphinx-action@master
    #     with:
    #       docs-folder: "docs_source/"
